import {
    Github as GithubIcon,
    Twitter as TwitterIcon,
    Instagram as InstagramIcon,
    Linkedin as LinkedinIcon
} from '@styled-icons/boxicons-logos';
import { Share as ShareIcon } from '@styled-icons/fluentui-system-filled';
import {
    Nextdotjs as NextjsIcon,
    Graphql as GraphQLIcon,
    ReactLogo as ReactjsIcon,
    Mongodb as MongodbIcon,
    Mysql as MysqlIcon,
    Nodedotjs as NodejsIcon,
    Express as ExpressIcon,
    Jsonwebtokens as JWTIcon,
    Vite as VitejsIcon,
    Jquery as JqueryIcon,
    Html5 as Html5Icon,
    Css3 as Css3Icon,
    Javascript as JavascriptIcon,
    Typescript as TypescriptIcon,
    Java as JavaIcon,
    Elixir as ElixirIcon,
    Rust as RustIcon,
    Strapi as StrapiIcon,
    Jamstack as JamstackIcon,
    Pm2 as Pm2Icon,
    Heroku as HerokuIcon,
    Vuedotjs as VuejsIcon,
    Nuxtdotjs as NuxtjsIcon,
    Nestjs as NestjsIcon,
    Adonisjs as AdonisjsIcon,
    Laravel as LaravelIcon,
    Php as PhpIcon,
    Vercel as VercelIcon,
    Digitalocean as DigitaloceanIcon,
    Redis as RedisIcon,
    Postgresql as PostgresqlIcon,
    Mariadb as MariadbIcon,
    Amazonaws as AwsIcon,
    Angularjs as AngularJsIcon,
    Angular as AngularIcon,
    Insomnia as InsomniaIcon,
    Postman as PostmanIcon,
    Jira as JiraIcon,
    Eslint as ESLintIcon,
    Notion as NotionIcon,
    Socketdotio as SocketIoIcon,
    Npm as NpmIcon,
    Reactrouter as ReactRouterIcon,
    Redux as ReduxIcon,
    Styledcomponents as StyledcomponentsIcon,
    Threedotjs as ThreejsIcon,
    Stripe as StripeIcon,

} from '@styled-icons/simple-icons';

const Icons = {
    GithubIcon,
    TwitterIcon,
    InstagramIcon,
    LinkedinIcon,
    NextjsIcon,
    GraphQLIcon,
    ReactjsIcon,
    AdonisjsIcon,
    AngularIcon,
    AngularJsIcon,
    AwsIcon,
    Css3Icon,
    DigitaloceanIcon,
    ESLintIcon,
    ElixirIcon,
    ExpressIcon,
    HerokuIcon,
    Html5Icon,
    InsomniaIcon,
    JWTIcon,
    JamstackIcon,
    JavaIcon,
    JavascriptIcon,
    JiraIcon,
    JqueryIcon,
    LaravelIcon,
    MongodbIcon,
    MariadbIcon,
    MysqlIcon,
    NestjsIcon,
    NotionIcon,
    NodejsIcon,
    NpmIcon,
    NuxtjsIcon,
    PhpIcon,
    Pm2Icon,
    PostgresqlIcon,
    PostmanIcon,
    ReactRouterIcon,
    RedisIcon,
    ReduxIcon,
    RustIcon,
    SocketIoIcon,
    StrapiIcon,
    StripeIcon,
    StyledcomponentsIcon,
    ThreejsIcon,
    TypescriptIcon,
    VercelIcon,
    VitejsIcon,
    VuejsIcon,
    ShareIcon
}

export {
    Icons
}